version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      bot-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend" 
    schedule:
      interval: "monthly"
    groups:
      frontend-dependencies:
        patterns:
          - "*"
