name: speedboat
version: '3.8'

services:
  db:
    build: ./docker/
    hostname: db
    container_name: db
    volumes:
      - speedboat_psql_data:/var/lib/postgresql/data
    environment:
      - ENV=production
    stop_grace_period: 1m
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    hostname: redis
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - speedboat_redis_data:/data
    ports:
      - "6379:6379"
  web:
    build: .
    command: python manage.py serve -r
    volumes:
      - .:/opt/rowboat
    ports:
      - "8686:8686"
    depends_on:
      - db
      - redis
  bot:
    build: .
    hostname: bot
    container_name: bot
    command: /opt/poetry/bin/poetry poe bot --env docker
    volumes:
      - .:/opt/rowboat
    ports:
      - "7171:7171"
    depends_on:
      - web
    links:
      - 'db:db'
  workers:
    build: .
    command: python manage.py workers
    volumes:
      - .:/opt/rowboat
    depends_on:
      - web

volumes:
  speedboat_psql_data:
  speedboat_redis_data:
