version: '3.8'
services:
  db:
    build: ./docker/
    volumes:
      - ~/.speedboatdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - ENV=production
    stop_grace_period: 1m
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ~/.speedboatdata:/data
  web:
    build: .
    command: python manage.py serve -r
    volumes:
      - .:/opt/rowboat
    ports:
      - "8686:8686"
    depends_on:
      - db
      - redis
  bot:
    build: .
    command: python manage.py bot -e docker
    volumes:
      - .:/opt/rowboat
    ports:
      - "7171:7171"
    depends_on:
      - web
  workers:
    build: .
    command: python manage.py workers
    volumes:
      - .:/opt/rowboat
    depends_on:
      - web
