name: speedboat

services:
  db:
    build: ./docker/
    volumes:
      - speedboat_psql_data:/var/lib/postgresql/data
    stop_grace_period: 1m
    ports:
      - "5432:5432"
  keydb:
    image: eqalpha/keydb:latest
    command: keydb-server --appendonly yes
    volumes:
      - speedboat_redis_data:/data
    ports:
      - "6379:6379"
  web:
    build: .
    command: python manage.py serve -r
    volumes:
      - .:/opt/rowboat
    depends_on:
      - db
      - keydb
    ports:
      - "8686:8686"
  bot:
    build: .
    command: /opt/poetry/bin/poetry poe bot --env docker
    volumes:
      - .:/opt/rowboat
    depends_on:
      - web
  workers:
    build: .
    command: python manage.py workers
    volumes:
      - .:/opt/rowboat
    depends_on:
      - web

volumes:
  speedboat_psql_data:
  speedboat_redis_data:
