[tool.poetry]
name = "speedboat"
version = "1.0.0"
description = "A Discord bot for managing large communities"
authors = [
    "Dj Isaac <contact@dejay.dev>"
]
license = "LICENSE.md"
readme = "README.md"
homepage = "https://docs.speedboat.rocks"
repository = "https://github.com/dejaydev/speedboat"
documentation = "https://docs.speedboat.rocks"

[tool.poetry.dependencies]
python = "^3.10"
betterdisco-py = {git = "https://github.com/elderlabs/betterdisco", extras=["performance"], rev = "bd380df97c65c3127cfc211203bc9dc6852983be"}
holster = {git = "https://github.com/elderlabs/holster"}
dominantcolors = {git = "https://github.com/wenmin-wu/dominant-colors-py"}
pygal = {git = "https://github.com/rafalkucharczyk/pygal", rev = "02c10a2919457bad4c83913a90c3aa0dd0ccb83a"}
click = "^8.1.3"
faust-cchardet = "^2.1.18"
dill = "^0.3.6"
emoji = "^2.5.1"
Flask = "^2.3.2"
greenlet = "^2.0.2"
humanize = "^4.6.0"
markovify = "^0.9.4"
oauthlib = "^3.2.2"
Pillow = "^9.5.0"
psycogreen = "^1.0.2"
psycopg2-binary = "^2.9.6"
pytz = "^2023.3"
pyyaml = "^6.0"
sentry-sdk = "^1.31.0"
redis = "^4.5.5"
requests-oauthlib = "^1.3.1"
urllib3 = "^2.0.3"
wheel = "^0.40.0"
rapidfuzz = "^3.1.1"
peewee = "^3.16.2"
datadog = "^0.45.0"
pynacl = "^1.5.0"

[tool.black]
line-length = 256

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
