[tool.poetry]
name = "speedboat"
version = "1.1.0"
description = "A Discord bot for managing large communities"
authors = [
    "Dj Isaac <contact@dejay.dev>"
]
license = "LICENSE.md"
readme = "README.md"
homepage = "https://docs.speedboat.rocks"
repository = "https://github.com/dejaydev/speedboat"
documentation = "https://docs.speedboat.rocks"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
aenum = "^3.1.15"
cairosvg = "^2.7.1"
certifi = "^2024.8.30"
click = "^8.1.7"
datadog = "^0.50.0"
dill = "^0.3.8"
emoji = "^2.12.1"
faust-cchardet = "^2.1.19"
Flask = "^2.3.3"
gevent-inotifyx = "^0.2"
humanize = "^4.10.0"
markovify = "^0.9.4"
modern-colorthief = "^0.1.6"
oauthlib = "^3.2.2"
peewee = "^3.17.6"
Pillow = "^10.4.0"
psycopg = {version = "^3.2.2", extras = ["binary"]}
pygal = "^3.0.5"
pynacl = "^1.5.0"
pytz = "^2024.2"
pyyaml = "^6.0.2"
rapidfuzz = "^3.9.7"
redis = "^5.0.8"
requests-oauthlib = "^2.0.0"
sentry-sdk = "^2.14.0"
urllib3 = "^2.2.3"
wheel = "^0.44.0"

# redis needs these, but for some reason i need to define them.
aiohttp = "^3.10.5"
async-timeout = "^4.0.3"

# https://github.com/elderlabs/BetterDisco/tree/staging/dooley
[tool.poetry.dependencies.betterdisco-py]
rev = "e6034adadce315e6fdb7e426f23ec65cfe5e3fe1"
git = "https://github.com/elderlabs/betterdisco"
extras = ["performance"]

[tool.poe.tasks.bot]
help = "Start the Speedbot bot"
args = [{ name = "env", required = false }]
script = "manage:bot()"

[tool.ruff]
line-length = 320 # This is the maximum for Ruff

[tool.ruff.lint]
ignore = ["E722"] # STOP IT 

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
